---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: 
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: author
  label: Author
  type: text
  hidden: false
  default: Johann
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default:
  - ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default:
  - ''
