baseurl = "/"
disqusShortname = "johannheadley-com"
googleAnalytics = "UA-44681567-1"
languageCode = "en-us"
paginate = 10
theme = "photo"
title = "Johann Headley Photography"
[[menu.main]]
name = "Blog"
url = "post/"
weight = -110
[[menu.main]]
name = "Home"
url = "/"
weight = -120
[params]
custom_css = []
custom_js = []
date_format = "Monday, Jan 2, 2006"
description = "Photographer who specialises in food photography. Based in Toronto, Canada"
name = "Johann Headley"
show_read_time = true
[params.about]
content = "My foray in the digital world intially started with web development. I always loved the visual medium – especially photography but never considered that as a career to channel my passions. After working on my wife's blog, <a href='https://www.oliveandmango.com/'>Olive & Mango</a> I really got an opportunity to dive right in. Over the years I have been able to push myself to the limits as I tackled new obstacles, coming out stronger every time. It's not often you get to do the thing you love and in this respect I'm living a dream."
hide = false
title = "The accidental photographer"
[params.contact]
address = ["25 Crewe Ave", "Toronto, ON M4C2H9", "Canada"]
content = "Use any of the methods below and I'll get back to you as soon as I can"
email = "johannd@icloud.com"
gmaps_address = "43.693505,-79.308399"
hide = false
phone = "‭647-692-7338"
title = "Let's work together!"
[params.contact.form]
email = "Email"
message = "Message"
name = "Name"
submit = "Send message"
[params.intro]
content = "Photography can say so much. It captures a momement in time, a feeling or can stir emotions. The challenge for a photographer is to capture those things, or in some cases surpass the reality. This is my goal.<br><br> <a class='cta_btn' href='#contact-form'>Hire Me</a>"
hide = false
title = "A Feast For The Eyes"
[params.portfolio]
hide = false
title = "Recent Work"
[[params.portfolio.gallery]]
description = "Close ups to bring out the details"
image = "fulls/15.jpg"
thumb = "thumbs/15.jpg"
title = "Ginger Shrimp And Soba"
[[params.portfolio.gallery]]
description = "Close ups to bring out the details"
image = "fulls/01.jpg"
thumb = "thumbs/01.jpg"
title = "Apple Tart"
[[params.portfolio.gallery]]
description = "Light and airy"
image = "fulls/02.jpg"
thumb = "thumbs/02.jpg"
title = "Crispy Skin Pork"
[[params.portfolio.gallery]]
description = "Light and airy"
image = "fulls/03.jpg"
thumb = "thumbs/03.jpg"
title = "Penne Alla Vodka"
[[params.portfolio.gallery]]
description = "Lorem ipsum dolor sit amet."
image = "fulls/04.jpg"
thumb = "thumbs/04.jpg"
title = "Greek Potato Salad"
[[params.portfolio.gallery]]
description = "Lorem ipsum dolor sit amet."
image = "fulls/05.jpg"
thumb = "thumbs/05.jpg"
title = "Brown Butter Nutella Bread"
[[params.portfolio.gallery]]
description = "Lorem ipsum dolor sit amet."
image = "fulls/06.jpg"
thumb = "thumbs/06.jpg"
title = "Apple Butter Spice Cake"
[[params.portfolio.gallery]]
description = "Lorem ipsum dolor sit amet."
image = "fulls/07.jpg"
thumb = "thumbs/07.jpg"
title = "Butternut Squash Kale Salad"
[[params.portfolio.gallery]]
description = "Lorem ipsum dolor sit amet."
image = "fulls/08.jpg"
thumb = "thumbs/08.jpg"
title = "Maple Pecan Cinnamon Rolls"
[[params.portfolio.gallery]]
description = "Lorem ipsum dolor sit amet."
image = "fulls/09.jpg"
thumb = "thumbs/09.jpg"
title = "Homemade Irish Cream"
[[params.portfolio.gallery]]
description = "Lorem ipsum dolor sit amet."
image = "fulls/10.jpg"
thumb = "thumbs/10.jpg"
title = "Charcuterie Board"
[[params.portfolio.gallery]]
description = "Lorem ipsum dolor sit amet."
image = "fulls/11.jpg"
thumb = "thumbs/11.jpg"
title = "Chocolate Hazelnut Tart"
[[params.portfolio.gallery]]
description = "Lorem ipsum dolor sit amet."
image = "fulls/12.jpg"
thumb = "thumbs/12.jpg"
title = "Salty Honey Pie"
[[params.portfolio.gallery]]
description = "Lorem ipsum dolor sit amet."
image = "fulls/13.jpg"
thumb = "thumbs/13.jpg"
title = "Pear Frangipani Tart"
[[params.portfolio.gallery]]
description = "Lorem ipsum dolor sit amet."
image = "fulls/14.jpg"
thumb = "thumbs/14.jpg"
title = "Blueberry Nice cream"
[params.recentposts]
hide = false
title = "Recent blog posts"
[params.sidebar]
avatar = "avatar.jpg"
bio = "Hello, I'm ***JOHANN HEADLEY***. I'm a **photographer** who specialises in food photography. Let's work together!"
copyright = ["Johann Headley"]
instagram = "__om__photography"
twitter = "johannheadley"
